title: Offsec-TX|CC
exclude: ['/scripts', '/Gemfile', '/Makefile', '/README.md']

permalink: pretty

collections:
  testcases:
    output: true
  wadcoms:
    output: true


defaults:
  - scope:
      path: '_testcases/web'
    values:
      layout: bin
  - scope:
      path: '_testcases/api'
    values:
      layout: bin
  - scope:
      path: '_testcases/mobile/apk'
    values:
      layout: bin
  - scope:
      path: '_testcases/mobile/ios'
    values:
      layout: bin
  - scope:
      path: '_testcases/network'
    values:
      layout: bin
  - scope:
      path: '_testcases/ad'
    values:
      layout: bin
  - scope:
      path: '_testcases/cloud/gcp'
    values:
      layout: bin
  - scope:
      path: '_testcases/cloud/aws'
    values:
      layout: bin
  - scope:
      path: '_testcases/cloud/azure'
    values:
      layout: bin
  - scope:
      path: '_testcases/os/linux'
    values:
      layout: bin
  - scope:
      path: '_testcases/os/windows'
    values:
      layout: bin
  - scope:
      path: '_wadcoms'
    values:
      layout: bin