title: Offsec-TX|CC
exclude: ['/scripts', '/Gemfile', '/Makefile', '/README.md']

permalink: pretty

collections:
  testcases:
    output: true
  wadcoms:
    output: true


defaults:
  - scope:
      path: '_testcases/web'
    values:
      layout: bin
  - scope:
      path: '_testcases/api'
    values:
      layout: bin
  - scope:
      path: '_testcases/mobile'
    values:
      layout: bin
  - scope:
      path: '_testcases/network'
    values:
      layout: bin
  - scope:
      path: '_testcases/ad'
    values:
      layout: bin
  - scope:
      path: '_testcases/cloud'
    values:
      layout: bin
  - scope:
      path: '_testcases/linux'
    values:
      layout: bin
  - scope:
      path: '_testcases/windows'
    values:
      layout: bin
  - scope:
      path: '_wadcoms'
    values:
      layout: bin