title: Offsec-TX
exclude: ['/Gemfile', '/Makefile', '/README.md']

permalink: pretty

collections:
  testcases:
    output: true


defaults:
  - scope:
      path: '_testcases'
    values:
      layout: bin