---
FTP:
  label: FTP
  description: You've found the FTP service open and need to know what you can do with it.

SSH:
  label: SSH
  description: You've found the SSH service open and need to know what you can do with it.

TELNET:
  label: TELNET
  description: You've found the TELNET service open and need to know what you can do with it.

SMTP:
  label: SMTP
  description: You've found the SMTP service open and need to know what you can do with it.

DNS:
  label: DNS
  description: You've found the DNS service open and need to know what you can do with it.

FINGER:
  label: FINGER
  description: You've found the FINGER service open and need to know what you can do with it.

KERBEROS:
  label: KERBEROS
  description: You've found the KERBEROS service open and need to know what you can do with it.

POP:
  label: POP
  description: You've found the POP service open and need to know what you can do with it.

PORTMAPPER:
  label: PORTMAPPER
  description: You've found the PORTMAPPER service open and need to know what you can do with it.

IDENT:
  label: IDENT
  description: You've found the IDENT service open and need to know what you can do with it.

NTP:
  label: NTP
  description: You've found the NTP service open and need to know what you can do with it.

MSRPC:
  label: MSRPC
  description: You've found the MSRPC service open and need to know what you can do with it.

NETBIOS:
  label: NETBIOS
  description: You've found the NETBIOS service open and need to know what you can do with it.

SMB:
  label: SMB
  description: You've found the SMB service open and need to know what you can do with it.

IMAP:
  label: IMAP
  description: You've found the IMAP service open and need to know what you can do with it.

SNMP:
  label: SNMP
  description: You've found the SNMP service open and need to know what you can do with it.

IRC:
  label: IRC
  description: You've found the IRC service open and need to know what you can do with it.

LDAP:
  label: LDAP
  description: You've found the LDAP service open and need to know what you can do with it.

IKE:
  label: IKE
  description: You've found the IKE service open and need to know what you can do with it.

MODBUS:
  label: MODBUS
  description: You've found the MODBUS service open and need to know what you can do with it.

REXEC:
  label: REXEC
  description: You've found the REXEC service open and need to know what you can do with it.

RSYNC:
  label: RSYNC
  description: You've found the RSYNC service open and need to know what you can do with it.

RTSP:
  label: RTSP
  description: You've found the RTSP service open and need to know what you can do with it.

IPMI:
  label: IPMI
  description: You've found the IPMI service open and need to know what you can do with it.

JAVA-RMI:
  label: JAVA-RMI
  description: You've found the JAVA-RMI service open and need to know what you can do with it.

MYSQL:
  label: MYSQL
  description: You've found the MYSQL service open and need to know what you can do with it.

MSSQL:
  label: MSSQL
  description: You've found the MSSQL service open and need to know what you can do with it.

NFS:
  label: NFS
  description: You've found the NFS service open and need to know what you can do with it.

POSTGRESQL:
  label: POSTGRESQL
  description: You've found the POSTGRESQL service open and need to know what you can do with it.

RDP:
  label: RDP
  description: You've found the RDP service open and need to know what you can do with it.

REDIS:
  label: REDIS
  description: You've found the REDIS service open and need to know what you can do with it.