---
FTP:
  label: FTP
  description: You've found the FTP service open and need to know what you can do with it.

SSH:
  label: SSH
  description: You've found the SSH service open and need to know what you can do with it.

